#!/usr/bin/env python3
# -*- coding: utf-8 -*-
#!/usr/bin/env python3
# -*- coding: utf-8 -*-
---
cluster_number: 5

original_dim: 286
inputdim1: 11
inputdim2: 26

latent_dim: 10
dim_layer1: 128
dim_layer2: 64
dim_layer3: 32
activation_function: 'relu'

cat_dim: 1

filepath: "plots/rmm-vae/v1/"

batch_size: 128
epochs: 100

reconstruction_loss_factor: 1


